export enum EN_CONFIG {
	QUANTITY_GAME_LOOP = 4,

	TIMING_LINE_CRITICAL_TOMATO = 3000,
	TIMING_LINE_CRITICAL_PEPPER = 3000,
	TIMING_LINE_CRITICAL_STRAWBERRY = 3000,

	TIMING_DRONE_MOVED_TOMATO = 7000,
	TIMING_DRONE_MOVED_PEPPER = 7000,
	TIMING_DRONE_MOVED_STRAWBERRY = 7000,

	TIMING_ULTRASOUND_TOMATO = 3000,
	TIMING_ULTRASOUND_PEPPER = 3000,
	TIMING_ULTRASOUND_STRAWBERRY = 3000,

	TIMING_DRONE_RETURNED_TOMATO = 7000,
	TIMING_DRONE_RETURNED_PEPPER = 7000,
	TIMING_DRONE_RETURNED_STRAWBERRY = 7000
}
