export enum EN_CONFIG {
	QUANTITY_GAME_LOOP = 7,

	TIMING_LOSS_BLOCK = 1000,

	TIMING_LINE_CRITICAL_TOMATO = 3000,
	TIMING_LINE_CRITICAL_PEPPER = 3000,
	TIMING_LINE_CRITICAL_STRAWBERRY = 3000,

	TIMING_DRONE_MOVED_TOMATO = 4000,
	TIMING_DRONE_MOVED_PEPPER = 4000,
	TIMING_DRONE_MOVED_STRAWBERRY = 4000,

	TIMING_ULTRASOUND_TOMATO = 3000,
	TIMING_ULTRASOUND_PEPPER = 3000,
	TIMING_ULTRASOUND_STRAWBERRY = 3000,

	TIMING_DRONE_RETURNED_TOMATO = 4000,
	TIMING_DRONE_RETURNED_PEPPER = 4000,
	TIMING_DRONE_RETURNED_STRAWBERRY = 4000
}
