export enum EN_CONFIG {
	TIMING_LINE_CRITICAL_TOMATO = 3000,
	TIMING_GAME_OVER = 2000,

	TIMING_BLACK_SCREEN = 2350,

	TIMING_GENERATE_TOMATO_GREEN = 700,
	TIMING_GENERATE_TOMATO_RED = 700,
	TIMING_GENERATE_TOMATO_DARK_GREEN = 700,
	TIMING_GENERATE_TIMEOUT_TOMATO_GREEN = 0,
	TIMING_GENERATE_TIMEOUT_TOMATO_RED = 1500,
	TIMING_GENERATE_TIMEOUT_TOMATO_DARK_GREEN = 2700,
	TIMING_GENERATE_ALL_TOMATOES_INTERVAL = 7000,

	TIMING_GENERATE_PEPPER_GREEN = 600,
	TIMING_GENERATE_PEPPER_RED = 600,
	TIMING_GENERATE_PEPPER_DARK_GREEN = 600,
	TIMING_GENERATE_TIMEOUT_PEPPER_GREEN = 0,
	TIMING_GENERATE_TIMEOUT_PEPPER_RED = 1200,
	TIMING_GENERATE_TIMEOUT_PEPPER_DARK_GREEN = 2400,
	TIMING_GENERATE_ALL_PEPPERS_INTERVAL = 6700,

	TIMING_GENERATE_STRAWBERRY_GREEN = 500,
	TIMING_GENERATE_STRAWBERRY_RED = 500,
	TIMING_GENERATE_STRAWBERRY_DARK_GREEN = 500,
	TIMING_GENERATE_TIMEOUT_STRAWBERRY_GREEN = 0,
	TIMING_GENERATE_TIMEOUT_STRAWBERRY_RED = 900,
	TIMING_GENERATE_TIMEOUT_STRAWBERRY_DARK_GREEN = 2100,
	TIMING_GENERATE_ALL_STRAWBERRIES_INTERVAL = 6400,

	TIMING_MOVE_COLLECTOR_LEFT = 150,
	TIMING_MOVE_COLLECTOR_RIGHT = 150
}
