export enum EN_CONFIG {
	TIMING_GAME_OVER = 2000,
	TIMING_VICTORY_BLOCK = 800,

	TIMING_BLACK_SCREEN = 2350,

	TIMING_TOMATO_LEVEL_TIMER = 40,
	TIMING_GENERATE_TOMATO_GREEN = 700,
	TIMING_GENERATE_TOMATO_RED = 700,
	TIMING_GENERATE_TOMATO_DARK_GREEN = 700,
	TIMING_GENERATE_TIMEOUT_TOMATO_GREEN = 0,
	TIMING_GENERATE_TIMEOUT_TOMATO_RED = 1500,
	TIMING_GENERATE_TIMEOUT_TOMATO_DARK_GREEN = 2700,
	TIMING_GENERATE_ALL_TOMATOES_INTERVAL = 7000,
	MINIMAL_POINTS_TOMATO = 5,

	TIMING_PEPPER_LEVEL_TIMER = 40,
	TIMING_GENERATE_PEPPER_GREEN = 600,
	TIMING_GENERATE_PEPPER_RED = 600,
	TIMING_GENERATE_PEPPER_DARK_GREEN = 600,
	TIMING_GENERATE_TIMEOUT_PEPPER_GREEN = 0,
	TIMING_GENERATE_TIMEOUT_PEPPER_RED = 1200,
	TIMING_GENERATE_TIMEOUT_PEPPER_DARK_GREEN = 2400,
	TIMING_GENERATE_ALL_PEPPERS_INTERVAL = 6700,
	MINIMAL_POINTS_PEPPER = 5,

	TIMING_STRAWBERRY_LEVEL_TIMER = 40,
	TIMING_GENERATE_STRAWBERRY_GREEN = 500,
	TIMING_GENERATE_STRAWBERRY_RED = 500,
	TIMING_GENERATE_STRAWBERRY_DARK_GREEN = 500,
	TIMING_GENERATE_TIMEOUT_STRAWBERRY_GREEN = 0,
	TIMING_GENERATE_TIMEOUT_STRAWBERRY_RED = 900,
	TIMING_GENERATE_TIMEOUT_STRAWBERRY_DARK_GREEN = 2100,
	TIMING_GENERATE_ALL_STRAWBERRIES_INTERVAL = 6400,
	MINIMAL_POINTS_STRAWBERRY = 5,

	TIMING_MOVE_COLLECTOR_LEFT = 110,
	TIMING_MOVE_COLLECTOR_RIGHT = 110
}
