export enum EN_CONFIG {
	TIMING_LINE_CRITICAL_TOMATO = 3000,
	TIMING_GAME_OVER = 2000,

	TIMING_BLACK_SCREEN = 2350,

	TIMING_GENERATE_TOMATO_GREEN = 700,
	TIMING_GENERATE_TOMATO_RED = 700,
	TIMING_GENERATE_TOMATO_DARK_GREEN = 700,
	TIMING_MOVE_COLLECTOR_LEFT = 150,
	TIMING_MOVE_COLLECTOR_RIGHT = 150
}
